In [1]:
# Import the numpy package under the name np

In [2]:
import numpy as np

In [3]:
# Create a null vector of size 10

In [4]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [5]:
# Create a vector with values ranging from 10 to 49

In [7]:
arr=np.arange(10,49)

In [8]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

In [9]:
# Find the shape of previous array in question 3

In [10]:
np.shape(arr)

(39,)

In [11]:
# Print the type of the previous array in question 3

In [15]:
arr.dtype

dtype('int32')

In [16]:
# Print the numpy version and the configuration

In [18]:
print(np.__version__)

1.18.5


In [19]:
print(np.__config__)

<module 'numpy.__config__' from 'C:\\Users\\Rana Awais\\anaconda3\\lib\\site-packages\\numpy\\__config__.py'>


In [20]:
# Print the dimension of the array in question 3

In [22]:
arr.ndim

1

In [23]:
# Create a boolean array with all the True values

In [24]:
arr<50

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [25]:
# Create a two dimensional array

In [29]:
arr_2d=np.arange(10).reshape(2,5)

In [30]:
arr_2d

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [27]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [28]:
 # Create a three dimensional array

In [31]:
arr_3d=np.arange(16).reshape(2,2,4)

In [32]:
arr_3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [33]:
arr_3d.ndim

3

In [34]:
np.ones((2,2,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [35]:
# Reverse a vector (first element becomes last)

In [36]:
arr=np.arange(11)

In [37]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
arr[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [39]:
# Create a null vector of size 10 but the fifth value which is 1

In [40]:
arr=np.zeros(11)

In [41]:
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [42]:
arr[5]=5

In [43]:
arr

array([0., 0., 0., 0., 0., 5., 0., 0., 0., 0., 0.])

In [44]:
# Create a 3x3 identity matrix

In [46]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [47]:
#arr = np.array([1, 2, 3, 4, 5])
#Convert the data type of the given array from int to float

In [48]:
arr=np.arange(1,6)

In [49]:
arr

array([1, 2, 3, 4, 5])

In [50]:
arr.dtype

dtype('int32')

In [51]:
arr=arr.astype(np.float32)

In [52]:
arr

array([1., 2., 3., 4., 5.], dtype=float32)

In [53]:
# arr1 = np.array([[1., 2., 3.],

#            [4., 5., 6.]])
# arr2 = np.array([[0., 4., 1.],

 #          [7., 2., 12.]])
# Multiply arr1 with arr2

In [59]:
 arr1 = np.array([[1., 2., 3.],

           [4., 5., 6.]])
arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])

In [60]:
arr1*arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

In [61]:
# arr1 = np.array([[1., 2., 3.],

 #           [4., 5., 6.]]) 

# arr2 = np.array([[0., 4., 1.],

  #          [7., 2., 12.]])
# Make an array by comparing both the arrays provided above

In [74]:
arr1=np.arange(1,7).reshape(2,1,3)

In [76]:
arr1

array([[[1, 2, 3]],

       [[4, 5, 6]]])

In [79]:
arr2=np.array([[0,4,1],[7,2,12]])

In [82]:
arr2.reshape(2,1,3)

array([[[ 0,  4,  1]],

       [[ 7,  2, 12]]])

In [83]:
# Extract all odd numbers from arr with values(0-9)

In [117]:
arr=np.arange(1,10,2)

In [118]:
arr

array([1, 3, 5, 7, 9])

In [112]:
#  Replace all odd numbers to -1 from previous array

In [119]:
arr

array([1, 3, 5, 7, 9])

In [121]:
arr[:]=-1

In [122]:
arr

array([-1, -1, -1, -1, -1])

In [123]:
# arr = np.arange(10)
# Replace the values of indexes 5,6,7 and 8 to 12

In [124]:
arr = np.arange(10)

In [125]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [127]:
arr[5:9]=12

In [128]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

In [129]:
# Create a 2d array with 1 on the border and 0 inside

In [130]:
arr=np.ones((4,4))

In [131]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [132]:
arr[1:3,1:3]=0

In [133]:
arr

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

In [134]:
# arr2d = np.array([[1, 2, 3],

#        [4, 5, 6], 

 #           [7, 8, 9]])
# Replace the value 5 to 12

In [135]:
 arr2d = np.array([[1, 2, 3],

        [4, 5, 6], 

            [7, 8, 9]])

In [136]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [137]:
arr2d[1][1]=12

In [138]:
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

In [139]:
# arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
# Convert all the values of 1st array to 64

In [148]:
 arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [149]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [152]:
arr3d[0]=64

In [153]:
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [154]:
# Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [164]:
arr2d=np.arange(9).reshape(3,3)

In [165]:
arr2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [168]:
arr2d[0]

array([0, 1, 2])

In [163]:
# Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [170]:
arr2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [169]:
arr2d[:2,2:]

array([[2],
       [5]])

In [171]:
# Create a 10x10 array with random values and find the minimum and maximum values

In [179]:
arr=np.random.randn(10,10)

In [180]:
arr

array([[-0.56181816,  1.41667887, -0.4610918 ,  1.50658348,  0.46633166,
        -1.46714078, -0.58066721,  0.95699312, -0.56208271,  1.59169282],
       [ 1.33969664,  0.5108485 ,  0.27965917,  0.59790652,  0.70253647,
         0.51420267,  1.91932133, -0.13787491,  0.03945685,  0.51276033],
       [-0.37520402, -0.69445084,  0.23072115,  0.36347852,  0.81089503,
        -0.55404066,  0.53840223, -2.03022379, -1.09067675, -1.28951238],
       [-0.42806802, -1.04023507, -0.00469068,  1.38874538, -0.33384511,
         0.19942098, -0.44416634,  2.37158699,  0.75771636, -0.57479771],
       [ 0.80740449,  0.76413226, -1.52659385,  0.92905691,  1.00346025,
        -0.18386544, -0.71816826, -0.29736642,  1.80282451, -0.1353172 ],
       [-1.7424282 , -1.19849173, -1.55002476,  0.86385515, -1.54225878,
        -0.5707302 , -0.30008932,  0.6958077 ,  1.20098215,  0.8904561 ],
       [ 0.57547479,  1.94999563,  0.67041289, -1.31144768, -1.4263957 ,
         0.28992242, -0.43535971,  2.05834746

In [182]:
arr.max()

2.3715869930690197

In [183]:
arr.min()

-2.030223785380635

In [184]:
# a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])¶
# Find the common items between a and b

In [187]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [189]:
np.intersect1d(a,b)

array([2, 4])

In [190]:
# names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)
# Find all the values from array data where the values from array names are not equal to Will

In [205]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)

In [206]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [207]:
data

array([[ 0.59557136, -0.28297715,  0.81836237,  0.86387899],
       [-0.42732347, -0.45897491, -0.77503742,  0.87016839],
       [-0.4425134 ,  0.02062274,  0.88762355, -2.22402404],
       [ 0.49397536, -1.39308441, -1.28207132,  0.28508636],
       [ 0.93358144, -0.31257973,  0.01262775, -1.94079574],
       [ 0.50705934,  0.71872396, -0.68870972,  0.18520574],
       [-0.77202527,  0.33561382,  2.43183849,  0.13955732]])

In [208]:
data[names!='Will']

array([[ 0.59557136, -0.28297715,  0.81836237,  0.86387899],
       [-0.42732347, -0.45897491, -0.77503742,  0.87016839],
       [ 0.49397536, -1.39308441, -1.28207132,  0.28508636],
       [ 0.50705934,  0.71872396, -0.68870972,  0.18520574],
       [-0.77202527,  0.33561382,  2.43183849,  0.13955732]])

In [195]:
# names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)
# Find all the values from array data where the values from array names are not equal to Will and Joe

In [209]:
value=(names!='Will')&(names!='Joe')

In [210]:
data[value]

array([[ 0.59557136, -0.28297715,  0.81836237,  0.86387899],
       [ 0.49397536, -1.39308441, -1.28207132,  0.28508636]])

In [211]:
# Swap axes of the array you created in Question 32

In [212]:
arr=np.arange(16).reshape(2,2,4)

In [213]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [214]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [215]:
# Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [227]:
arr=np.arange(10)

In [228]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [229]:
sqr_arr=np.sqrt(arr)

In [230]:
sqr_arr

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [231]:
np.where(sqr_arr<0.5,0,sqr_arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [232]:
# Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [233]:
arr1=np.random.randn(12)

In [234]:
arr1

array([ 0.92918389, -0.99738595, -0.16818672, -0.61468672, -0.20490446,
        1.35624189,  0.20357753,  0.07985634,  0.00782309, -1.81533871,
       -0.68399575, -1.32488546])

In [235]:
arr2=np.random.randn(12)

In [236]:
arr2

array([ 0.90111723, -1.59184112,  0.74713874,  0.28229514,  0.05291458,
        1.47676735,  0.28949873, -0.99637905, -1.09080779, -0.13985405,
        1.52566001, -0.62561714])

In [237]:
np.maximum(arr1,arr2)

array([ 0.92918389, -0.99738595,  0.74713874,  0.28229514,  0.05291458,
        1.47676735,  0.28949873,  0.07985634,  0.00782309, -0.13985405,
        1.52566001, -0.62561714])

In [238]:
# names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
# Find the unique names and sort them out!

In [239]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [244]:
value=np.unique(names)

In [245]:
value

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [246]:
np.sort(value)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [247]:
# a = np.array([1,2,3,4,5]) b = np.array([5,6,7,8,9])
# From array a remove all items present in array b

In [248]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

In [249]:
np.setxor1d(a,b)

array([1, 2, 3, 4, 6, 7, 8, 9])

In [251]:
# Following is the input NumPy array delete column two and insert following new column in its place.
 # sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])

# newColumn = numpy.array([[10,10,10]])

In [253]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])

newColumn = np.array([[10,10,10]])

In [254]:
sampleArray

array([[34, 43, 73],
       [82, 22, 12],
       [53, 94, 66]])

In [255]:
newColumn

array([[10, 10, 10]])

In [261]:
sampleArray[:,1]=newColumn

In [262]:
sampleArray

array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])

In [263]:
# x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])
# Find the dot product of the above two matrix

In [264]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])

In [265]:
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [266]:
np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [267]:
# Generate a matrix of 20 random values and find its cumulative sum

In [268]:
arr=np.random.randn(20)

In [269]:
arr

array([ 1.03263531, -0.10725188,  1.52033311,  1.46024152, -1.65409544,
        0.66105464,  0.09532031, -0.28717652, -1.0534396 , -0.63448495,
        0.88817874, -0.86052874, -0.05539575,  1.79374318,  1.11190268,
       -1.18586696,  0.85712185,  0.36146224,  0.06079953,  1.47990869])

In [270]:
np.cumsum(arr)

array([1.03263531, 0.92538343, 2.44571654, 3.90595806, 2.25186263,
       2.91291727, 3.00823758, 2.72106106, 1.66762145, 1.0331365 ,
       1.92131524, 1.0607865 , 1.00539075, 2.79913392, 3.91103661,
       2.72516965, 3.5822915 , 3.94375374, 4.00455327, 5.48446196])

In [274]:
arr1=np.random.randint(20,size=(5,4))

In [275]:
arr1

array([[ 0, 18, 18,  4],
       [ 2,  6, 11, 11],
       [ 5,  3,  7,  2],
       [18,  1, 15,  3],
       [ 7, 17, 11,  7]])