In [1]:
import numpy as np

In [2]:
# Convert a 1D array to a 2D array with 2 rows?¶
# Desired output::
# array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])

In [3]:
arr=np.arange(10)

In [4]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [7]:
# How to stack two arrays vertically?
# Desired Output::
# array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [1, 1, 1, 1, 1], [1, 1, 1, 1, 1

In [10]:
arr=np.arange(10).reshape(2,5)

In [11]:
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [13]:
arr1=np.ones((2,5))

In [14]:
arr1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
np.vstack((arr,arr1))

array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
# How to stack two arrays horizontally?¶
# Desired Output::
# array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1], [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [19]:
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [20]:
arr1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [21]:
np.hstack((arr,arr1))

array([[0., 1., 2., 3., 4., 1., 1., 1., 1., 1.],
       [5., 6., 7., 8., 9., 1., 1., 1., 1., 1.]])

In [23]:
 #How to convert an array of arrays into a flat 1d array?¶
# Desired Output::
# array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [25]:
arr.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
# How to Convert higher dimension into one dimension?
# Desired Output::
# array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])

In [29]:
arr=np.arange(15).reshape(5,1,3)

In [30]:
arr

array([[[ 0,  1,  2]],

       [[ 3,  4,  5]],

       [[ 6,  7,  8]],

       [[ 9, 10, 11]],

       [[12, 13, 14]]])

In [31]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [32]:
# Question:7
# Create 5x5 an array and find the square of an array?

In [33]:
arr=np.arange(25).reshape(5,5)

In [34]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [35]:
np.square(arr)

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]], dtype=int32)

In [36]:
# Create 5x6 an array and find the mean?

In [38]:
arr=np.arange(30).reshape(5,6)

In [39]:
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [40]:
np.mean(arr)

14.5

In [41]:
# Find the standard deviation of the previous array in Q8

In [42]:
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [43]:
np.std(arr)

8.65544144839919

In [44]:
# Find the transpose of the previous array in Q8?

In [45]:
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [46]:
arr.T

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

In [47]:
np.transpose(arr)

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

In [48]:
# Create a 4x4 an array and find the sum of diagonal elements?

In [49]:
arr=np.arange(16).reshape(4,4)

In [50]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [54]:
diagonal=np.diag(arr)

In [55]:
diagonal

array([ 0,  5, 10, 15])

In [56]:
diagonal.sum()

30

In [57]:
# Find the determinant of the previous array in Q12?

In [58]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [59]:
np.linalg.det(arr)

0.0

In [60]:
# Find the 5th and 95th percentile of an array?

In [63]:
arr=np.array([20,12,35,44,55])

In [64]:
arr

array([20, 12, 35, 44, 55])

In [67]:
np.percentile(arr,5)

13.600000000000001

In [68]:
np.percentile(arr,95)

52.8

In [69]:
# How to find if a given array has any null values?

In [70]:
arr=np.array([1,2,3,4,5,0,6,7,8,9,0,0,10,11,12])